### ISSUE TITLE
In z3c.form >= 3.2.11, the SelectWidget.items method is now a @property

### ISSUE THREAD

**Issue by gbastien** [collective/collective.z3cform.select2#3]
Hi @mpeeters @vincentfretin 

As it is overrided in SingleSelect2Widget(SelectWidget), we need to make it a @property or it fails with "TypeError: 'list' object is not callable".

See https://github.com/zopefoundation/z3c.form/commit/5401f617e5be591c616d3ae7707b073a5a835064

I would make the package require z3c.form >= 3.2.11, is this OK?

@mpeeters maybe we can fix Travis then make a release with your last changes before implementing this and make another release?

Gauthier

**Comment by vincentfretin** [comment]
Hi @gbastien, please go ahead and make the changes. Be sure to add the right requirement in setup.py though.

**Comment by mpeeters** [comment]
PR #4

**Comment by gbastien** [comment]
@mpeeters thank you for the merge.

@vincentfretin I will release a 1.4.0 version as this is some breaking change.  We may still backport to some 1.3.x versions in case z3c.form 3.2.11 can not be used.

Gauthier
