### ISSUE TITLE
Not compatible with eea.facetednavigation 10+

### ISSUE THREAD

**Issue by gbastien** [collective/collective.z3cform.select2#5]
Hi @vincentfretin @mpeeters @bsuttor 

the package does not start with eea.facetednavigation 10+ because the faceted widget (https://github.com/collective/collective.z3cform.select2/blob/master/src/collective/z3cform/select2/browser/select2widget.py) fails to load because the ZCML registration changed.

I would like to adapt that and release a version 1.5, and make a 1.4.x branch.

What do you think?  I think it is not easy to make it work for both faceted 10- and 10+...

Gauthier

**Comment by vincentfretin** [comment]
Hi, you should even do a 2.0.0 version in my opinion.

**Comment by gbastien** [comment]
OK, I will propose a PR with version 2.0.0 and faceted widget working with facetednavigation 10+.

We can create a 1.4.x branch for eventual backports if necessary, before merging the PR.

Thank you for feed back.

Gauthier

**Comment by gbastien** [comment]
Closed by #6
