### ISSUE TITLE
select2 taxonomy widget wrongly used by default

### ISSUE THREAD

**Issue by gbastien** [collective/collective.z3cform.select2#7]
Hi @vincentfretin @cedricmessiant 

I would like to solve the problem about select2 widget being used fir every schema.List fields.

This is because of https://github.com/collective/collective.z3cform.select2/blob/master/src/collective/z3cform/select2/widget/adapters.zcml#L8

I would like to move this to collective.taxonomy directly or people need to use plone.autoform widget directive to use it on their taxonomy fields but I am not happy with it being enabled automagically...

I would like to remove it and maybe adapt README.rst to explain how to use it.

Are you using it for now?

Thank you!

Gauthier

**Comment by vincentfretin** [comment]
Hi,

I'm using `<include package="collective.z3cform.select2" file="minimal.zcml" />` in one project and I want default widget to be select2.
You don't need to change anything, you can already opt-out. This is explained in the README. I did it in
https://github.com/collective/collective.z3cform.select2/commit/4bc7106f3ac091fc46c3c1223032ea8f7a0b3958

You can use:

    <include package="collective.z3cform.select2" file="minimal.zcml" />
    <include package="z3c.unconfigure" file="meta.zcml" />
    <unconfigure package="collective.z3cform.select2.widget">
      <include file="adapters.zcml" />
    </unconfigure>

or I think simply:

    <exclude package="collective.z3cform.select2.widget" file="adapters.zcml" />
    <include package="collective.z3cform.select2" file="minimal.zcml" />

If you really want, you can change minimal.zcml to not include widget/adapters.zcml and you will need to include widget/adapters.zcml explicitly in your project if you want the default widget behavior.

You shouldn't introduce a new collective.z3cform.select2 dependency on collective.taxonomy.

**Comment by gbastien** [comment]
Hi @vincentfretin 

yes, I would better comment adapters.zcml in widget/configure.zcml so it is not loaded and explain how to enable it instead include it and explain how to exclude it ;-)

I will propose a PR, and indeed you will have to include the adapters.zcml in your package zcml to enable it.

Thank you for response,

Gauthier

**Comment by laulaz** [comment]
The solution proposed by @gbastien has been implemented.
